[default]
port = 8080
surreal_username = "pokedraft_api"
surreal_db_name = "pokedraft"
surreal_db_user_type="Database"

[dev]
surreal_namespace = "dev"
surreal_addr = "localhost:8000"

[release]
surreal_namespace = "prod"
surreal_addr = "surrealdb:8000"
